### ISSUE TITLE
Organize content with thumbnail image and cards

### ISSUE THREAD

**Issue by blaylockbk** [ngblaylock/blaylock-family-history#1]
This might be a good way to organize the content, rather than a list
https://getbootstrap.com/docs/4.0/components/card/

**Comment by ngblaylock** [comment]
Yup. I agree. Go for it. I just did a list to get it out the door. Plus, I want to see what it is like when you work on it too. I haven't collaborated on anything with GitHub.

**Comment by blaylockbk** [comment]
Ok. I might do something on the train home today.

*Brian*
